# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-01 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.TextField(null=True)),
                ('like', models.IntegerField(null=True)),
                ('page_view', models.IntegerField(null=True)),
                ('comment_usr', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.ImageField(null=True, upload_to='static/upload/text')),
                ('content', models.TextField()),
                ('time', models.CharField(max_length=30)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'texts',
            },
        ),
        migrations.CreateModel(
            name='textType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'texttype',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('uemail', models.EmailField(max_length=254)),
                ('upwd', models.CharField(max_length=20)),
                ('uphone', models.CharField(max_length=11)),
                ('realname', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20, null=True)),
                ('hobby', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='texts',
            name='texttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.textType'),
        ),
        migrations.AddField(
            model_name='texts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Texts'),
        ),
    ]
