# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-02 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
